// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmsFunvWwBBP3q92VrqhIrfIzD61Qkp5Q',
    appId: '1:3111184968:web:3fbc65903b5c718d41067d',
    messagingSenderId: '3111184968',
    projectId: 'koskaki-pjbl',
    authDomain: 'koskaki-pjbl.firebaseapp.com',
    storageBucket: 'koskaki-pjbl.firebasestorage.app',
    measurementId: 'G-NVD8KN7E5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtz6HVfLRYKdxpWb416HVVJQ5J4u8lhcE',
    appId: '1:3111184968:android:47d3f3eb3d0b018f41067d',
    messagingSenderId: '3111184968',
    projectId: 'koskaki-pjbl',
    storageBucket: 'koskaki-pjbl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9d5bghMZ3li35P6wZVBMDhbhi2isSwQ',
    appId: '1:3111184968:ios:664d5041d0e829cc41067d',
    messagingSenderId: '3111184968',
    projectId: 'koskaki-pjbl',
    storageBucket: 'koskaki-pjbl.firebasestorage.app',
    iosBundleId: 'com.example.koskaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9d5bghMZ3li35P6wZVBMDhbhi2isSwQ',
    appId: '1:3111184968:ios:664d5041d0e829cc41067d',
    messagingSenderId: '3111184968',
    projectId: 'koskaki-pjbl',
    storageBucket: 'koskaki-pjbl.firebasestorage.app',
    iosBundleId: 'com.example.koskaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmsFunvWwBBP3q92VrqhIrfIzD61Qkp5Q',
    appId: '1:3111184968:web:31f5b4cd8c50fa0341067d',
    messagingSenderId: '3111184968',
    projectId: 'koskaki-pjbl',
    authDomain: 'koskaki-pjbl.firebaseapp.com',
    storageBucket: 'koskaki-pjbl.firebasestorage.app',
    measurementId: 'G-19QQHSH3E0',
  );
}
